In [1]:
#lets import in the libraries
import pandas as pd
import matplotlib.cm as cmx
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt; plt.rcdefaults()
import seaborn as sns; sns.set()
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols    
import seaborn as sns 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline

In [2]:
data=pd.read_csv("merged_data_3.csv",encoding="latin-1")

In [3]:
dataReplace=data.replace("-",np.nan)

In [4]:
dataReplace.head()

,Unnamed: 0,Country,Year,School age population (thousands),urban,pre-primary,primary,secondary,NWA_Basic water service,NWA_Limited water service,...,PH_Basic hygiene service,PH_Limited hygiene service,PH_No hygiene service,SH_Basic hygiene service,SH_Limited hygiene service,SH_No hygiene service,EDULIT_IND,Indicator,TIME,Value
0,0,Afghanistan,2016,13299.24707,27.13200188,15.83112907,45.34436417,38.82450485,0,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Algeria,2016,8512.623047,71.30400085,10.01031017,42.57013321,47.41955566,93.30671292,0,...,97.78,NaN,NaN,99.3,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Andorra,2016,NaN,NaN,NaN,NaN,NaN,100,0,...,100,0,0,100,0,0,NaN,NaN,NaN,NaN
3,3,Argentina,2016,10821.82813,91.89299774,20.48494911,40.30799484,39.20705414,0,89.9,...,NaN,NaN,NaN,NaN,NaN,NaN,LR_AG15T99,"Adult literacy rate, population 15+ years, bot...",2013.0,99.12195
4,7,Australia,2016,4197.949219,89.55399323,7.541897297,51.23599625,41.22210693,100,0,...,100,0,0,100,0,0,NaN,NaN,NaN,NaN

In [5]:
dataReplace.columns

Index(['Unnamed: 0', 'Country', 'Year', 'School age population (thousands)',
       'urban', 'pre-primary', 'primary', 'secondary',
       'NWA_Basic water service', 'NWA_Limited water service',
       'NWA_No water service', 'UWA_Basic water service',
       'UWA_Limited water service', 'UWA_No water service',
       'RWA_Basic water service ', 'RWA_Limited water service ',
       'RWA_No water service ', 'PPWA_Basic water service ',
       'PPWA_Limited water service ', 'PPWA_No water service ',
       'PWA_Basic water service', 'PWA_Limited water service ',
       'PWA_No water service ', 'SWA_Basic water service ',
       'SWA_Limited water service ', 'SWA_No water service',
       'NS_Basic sanitation service', 'NS_Limited sanitation service',
       'NS_No sanitation service ', 'US_Basic sanitation service',
       'US_Limited sanitation service', 'US_No sanitation service ',
       'RS_Basic sanitation service', 'RS_Limited sanitation service',
       'RS_No sanitation service ', 'PPS_Basic sanitation service',
       'PPS_Limited sanitation service', 'PPS_No sanitation service ',
       'PS_Basic sanitation service', 'PS_Limited sanitation service',
       'PS_No sanitation service ', 'SS_Basic sanitation service',
       'SS_Limited sanitation service', 'SS_No sanitation service ',
       'NH_Basic hygiene service', 'NH_Limited hygiene service ',
       'NH_No hygiene service', 'UH_Basic hygiene service',
       'UH_Limited hygiene service ', 'UH_No hygiene service ',
       'RH_Basic hygiene service', 'RH_Limited hygiene service',
       'RH_No hygiene service ', 'PPH_Basic hygiene service',
       'PPH_Limited hygiene service ', 'PPH_No hygiene service ',
       'PH_Basic hygiene service', 'PH_Limited hygiene service ',
       'PH_No hygiene service ', 'SH_Basic hygiene service',
       'SH_Limited hygiene service ', 'SH_No hygiene service ', 'EDULIT_IND',
       'Indicator', 'TIME', 'Value'],
      dtype='object')

In [29]:
Usedata=dataReplace[['NWA_Basic water service','NS_Basic sanitation service','NH_Basic hygiene service', 'Value' ]]

In [30]:
Usedata.shape

(147, 4)

In [26]:
#The relationship between water, sanication, hygeine---person  oorecoeff

In [31]:
UsedataValid=Usedata.dropna()

In [32]:
UsedataValid.shape

(38, 4)

In [10]:
print(UsedataValid)

    NWA_Basic water service NS_Basic sanitation service  \
5                       100                         100
6                       100                         100
7               73.63671704                 58.55357143
8                       100                         100
15                        0                 83.90410959
16              52.56573529                 70.43392955
17              41.59394997                 47.87229332
19                        0                       38.85
26                      100                         100
27                     55.2                        61.4
40               50.5246315                 82.72727273
52                     73.8                     60.2952
58              10.03837335                           0
60              58.62468394                 81.53165867
61                      100                 91.91586998
63                    65.69                       34.12
66                    83.26                       83.26
70                      100                         100
79                        0                 70.26428571
80                    99.66                       99.66
85                        0                 74.70238095
89                        0                        47.5
105                73.06602                 68.46545391
106             50.30711702                 39.00588761
108                     100                         100
110                     100                 94.47142857
112                   44.16                 88.37892235
118                   31.56                           0
119             71.97148813                 73.72849507
121             61.55660377                 12.32227488
122                     100                         100
124                     100                         100
129                     100                         100
133             78.69127517                       44.22
135                    69.5                   99.482534
138                       0                 47.10342835
141             89.51544656                 91.55438254
146                   64.09                           0

    NH_Basic hygiene service     Value
5                        100  99.78936
6                        100  97.06668
7                         44  61.01554
8                        100  99.60000
15                  61.02142  91.48424
16                      18.4  34.59940
17               19.24729898  61.56973
19                     40.95  78.05509
26                       100  96.53849
27                         0  94.18625
40               86.82440186  93.29463
52                        12  99.58619
58                         0  32.00384
60               12.48655573  85.46442
61               99.42256214  99.10000
63                     41.62  95.11622
66                     83.26  88.10000
70                       100  95.58582
79                         0  65.14537
80                     99.66  93.73470
85                         0  93.96285
89                      15.4  56.03900
105                        0  93.70795
106              45.88626819  96.39800
108                      100  90.63299
110                      100  99.35989
112                    47.91  70.80413
118               22.0858824  42.81750
119               73.4429632  98.84151
121                        0  32.42617
122                      100  96.54808
124                      100  99.70000
129                      100  98.07913
133               25.5033557  99.80000
135                        0  79.03643
138                     22.5  77.88723
141              89.46342941  99.99486
146                        0  88.69342

In [11]:
type(UsedataValid)

pandas.core.frame.DataFrame

In [12]:
print(UsedataValid)

    NWA_Basic water service NS_Basic sanitation service  \
5                       100                         100
6                       100                         100
7               73.63671704                 58.55357143
8                       100                         100
15                        0                 83.90410959
16              52.56573529                 70.43392955
17              41.59394997                 47.87229332
19                        0                       38.85
26                      100                         100
27                     55.2                        61.4
40               50.5246315                 82.72727273
52                     73.8                     60.2952
58              10.03837335                           0
60              58.62468394                 81.53165867
61                      100                 91.91586998
63                    65.69                       34.12
66                    83.26                       83.26
70                      100                         100
79                        0                 70.26428571
80                    99.66                       99.66
85                        0                 74.70238095
89                        0                        47.5
105                73.06602                 68.46545391
106             50.30711702                 39.00588761
108                     100                         100
110                     100                 94.47142857
112                   44.16                 88.37892235
118                   31.56                           0
119             71.97148813                 73.72849507
121             61.55660377                 12.32227488
122                     100                         100
124                     100                         100
129                     100                         100
133             78.69127517                       44.22
135                    69.5                   99.482534
138                       0                 47.10342835
141             89.51544656                 91.55438254
146                   64.09                           0

    NH_Basic hygiene service     Value
5                        100  99.78936
6                        100  97.06668
7                         44  61.01554
8                        100  99.60000
15                  61.02142  91.48424
16                      18.4  34.59940
17               19.24729898  61.56973
19                     40.95  78.05509
26                       100  96.53849
27                         0  94.18625
40               86.82440186  93.29463
52                        12  99.58619
58                         0  32.00384
60               12.48655573  85.46442
61               99.42256214  99.10000
63                     41.62  95.11622
66                     83.26  88.10000
70                       100  95.58582
79                         0  65.14537
80                     99.66  93.73470
85                         0  93.96285
89                      15.4  56.03900
105                        0  93.70795
106              45.88626819  96.39800
108                      100  90.63299
110                      100  99.35989
112                    47.91  70.80413
118               22.0858824  42.81750
119               73.4429632  98.84151
121                        0  32.42617
122                      100  96.54808
124                      100  99.70000
129                      100  98.07913
133               25.5033557  99.80000
135                        0  79.03643
138                     22.5  77.88723
141              89.46342941  99.99486
146                        0  88.69342

In [19]:
len(UsedataValid)

38

In [13]:
#change the datatype into float
new_d=pd.DataFrame(UsedataValid,dtype=np.float)

In [44]:
print(new_d)

     NWA_Basic water service  NS_Basic sanitation service  \
5                 100.000000                   100.000000
6                 100.000000                   100.000000
7                  73.636717                    58.553571
8                 100.000000                   100.000000
15                  0.000000                    83.904110
16                 52.565735                    70.433930
17                 41.593950                    47.872293
19                  0.000000                    38.850000
26                100.000000                   100.000000
27                 55.200000                    61.400000
40                 50.524631                    82.727273
52                 73.800000                    60.295200
58                 10.038373                     0.000000
60                 58.624684                    81.531659
61                100.000000                    91.915870
63                 65.690000                    34.120000
66                 83.260000                    83.260000
70                100.000000                   100.000000
79                  0.000000                    70.264286
80                 99.660000                    99.660000
85                  0.000000                    74.702381
89                  0.000000                    47.500000
105                73.066020                    68.465454
106                50.307117                    39.005888
108               100.000000                   100.000000
110               100.000000                    94.471429
112                44.160000                    88.378922
118                31.560000                     0.000000
119                71.971488                    73.728495
121                61.556604                    12.322275
122               100.000000                   100.000000
124               100.000000                   100.000000
129               100.000000                   100.000000
133                78.691275                    44.220000
135                69.500000                    99.482534
138                 0.000000                    47.103428
141                89.515447                    91.554383
146                64.090000                     0.000000

     NH_Basic hygiene service     Value
5                  100.000000  99.78936
6                  100.000000  97.06668
7                   44.000000  61.01554
8                  100.000000  99.60000
15                  61.021420  91.48424
16                  18.400000  34.59940
17                  19.247299  61.56973
19                  40.950000  78.05509
26                 100.000000  96.53849
27                   0.000000  94.18625
40                  86.824402  93.29463
52                  12.000000  99.58619
58                   0.000000  32.00384
60                  12.486556  85.46442
61                  99.422562  99.10000
63                  41.620000  95.11622
66                  83.260000  88.10000
70                 100.000000  95.58582
79                   0.000000  65.14537
80                  99.660000  93.73470
85                   0.000000  93.96285
89                  15.400000  56.03900
105                  0.000000  93.70795
106                 45.886268  96.39800
108                100.000000  90.63299
110                100.000000  99.35989
112                 47.910000  70.80413
118                 22.085882  42.81750
119                 73.442963  98.84151
121                  0.000000  32.42617
122                100.000000  96.54808
124                100.000000  99.70000
129                100.000000  98.07913
133                 25.503356  99.80000
135                  0.000000  79.03643
138                 22.500000  77.88723
141                 89.463429  99.99486
146                  0.000000  88.69342

In [70]:
#Pearson Coefficient
new_d.corr(method='pearson')

,NWA_Limited water service,NS_Limited sanitation service,NH_Limited hygiene service,Value
NWA_Limited water service,1.000000,0.110481,0.430885,-0.235524
NS_Limited sanitation service,0.110481,1.000000,0.315514,-0.489173
NH_Limited hygiene service,0.430885,0.315514,1.000000,-0.233648
Value,-0.235524,-0.489173,-0.233648,1.000000

In [74]:
Person=new_d.corr(method='pearson')

In [71]:
UsedataValid.to_csv('PearsonCorr.csv')

In [ ]:
#PictureDraw

In [83]:
from pyecharts import options as opts
from pyecharts.charts import HeatMap
from pyecharts.render import make_snapshot
from snapshot_selenium import snapshot

In [86]:
heatmap=HeatMap()
rowdata=['NWA','NS','NH','Value']
columndata=['Value','NH','NS','NWA']
Personvalue = [[0,0,-0.235524],[0,1,-0.489173],[0,2,-0.2336],[0,3,1],[1,0,0.430885],[1,1,0.3155],[1,2,1],[1,3,-0.2336],[2,0,0.11048],[2,1,1],[2,2,0.3155],[2,3,-0.4891],[3,0,1],[3,1,0.11048],[3,2,0.4308],[3,3,-0.2355]]
heatmap.add_xaxis(
                  rowdata
                  )
heatmap.add_yaxis(
                 "Factors",
                  columndata, 
                  Personvalue,
                  label_opts=opts.LabelOpts(is_show=True,font_size=14,position="inside",font_family="Times New Roman"),
                  )
heatmap.set_global_opts(
            yaxis_opts=opts.AxisOpts(
                name="Candidate Factors",
                name_location="center",
                # 坐标轴名称的文字样式--刻度和名称
                axislabel_opts=opts.LabelOpts(font_family="Times New Roman"),
                
                name_textstyle_opts=opts.TextStyleOpts(font_size=18,font_family="Times New Roman"),
                name_gap=25,
                
                axistick_opts=opts.AxisTickOpts(
                is_inside=True,
                ),
            ),
            xaxis_opts=opts.AxisOpts(
                name="Candidate Factors",
                name_location="center",
                # 坐标轴名称的文字样式--刻度和名称
                axislabel_opts=opts.LabelOpts(font_family="Times New Roman"),
                
                name_textstyle_opts=opts.TextStyleOpts(font_size=18,font_family="Times New Roman"),
                name_gap=15,
                
                axistick_opts=opts.AxisTickOpts(
                is_inside=True,
                ),
            ),
         
            visualmap_opts=opts.VisualMapOpts(type_="color",min_=-1,max_=1, pos_right=20),
            
)
make_snapshot(snapshot, heatmap.render(path=r"C:\Users\20194289\Desktop\DataScience\OneDrive_1_2019114\OneDrive_2_2019117\Heapmap2.html"),"C:\\Users\\20194289\\Desktop\\DataScience\\OneDrive_1_2019114\\OneDrive_2_2019117\\Heapmap2.pdf",pixel_ratio=10)

In [92]:
Usedata2=dataReplace[['Country','NWA_Limited water service','NS_Limited sanitation service','NH_Limited hygiene service ', 'Value' ]]

In [110]:
from pyecharts.charts import Scatter
import execjs

ModuleNotFoundError: No module named 'execjs'

In [114]:
!conda install PyExecJs
#只支持python2

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyexecjs

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

In [115]:
Scatter1=Scatter()
Scatter1.add_xaxis(Usedata2['NWA_Limited water service'])
Scatter1.add_yaxis("Value", 
                  ),
Scatter1.set_global_opts(
            title_opts=opts.TitleOpts(title="Scatter-VisualMap(Color)"),
            visualmap_opts=opts.VisualMapOpts(max_=150),)

In [116]:

make_snapshot(snapshot, Scatter1.render(path=r"C:\Users\20194289\Desktop\DataScience\OneDrive_1_2019114\OneDrive_2_2019117\Scatter.html"),"C:\\Users\\20194289\\Desktop\\DataScience\\OneDrive_1_2019114\\OneDrive_2_2019117\\Scatter.pdf",pixel_ratio=10)

In [15]:
#Regression  Water===
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [16]:
X=new_d[['NH_Basic hygiene service','NS_Basic sanitation service', 'Value']]

In [17]:
Y=new_d['NWA_Basic water service']

In [18]:
X=sm.add_constant(X)
est=sm.OLS(Y,X).fit()
est.summary()

C:\Users\20194289\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

<class 'statsmodels.iolib.summary.Summary'>
"""
                               OLS Regression Results
===================================================================================
Dep. Variable:     NWA_Basic water service   R-squared:                       0.499
Model:                                 OLS   Adj. R-squared:                  0.455
Method:                      Least Squares   F-statistic:                     11.31
Date:                     Fri, 08 Nov 2019   Prob (F-statistic):           2.68e-05
Time:                             10:07:15   Log-Likelihood:                -176.12
No. Observations:                       38   AIC:                             360.2
Df Residuals:                           34   BIC:                             366.8
Df Model:                                3
Covariance Type:                 nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                           6.6128     18.918      0.350      0.729     -31.833      45.058
NH_Basic hygiene service        0.4513      0.152      2.975      0.005       0.143       0.760
NS_Basic sanitation service     0.0961      0.207      0.465      0.645      -0.324       0.516
Value                           0.3176      0.270      1.178      0.247      -0.230       0.866
==============================================================================
Omnibus:                        8.488   Durbin-Watson:                   2.340
Prob(Omnibus):                  0.014   Jarque-Bera (JB):                7.417
Skew:                          -1.034   Prob(JB):                       0.0245
Kurtosis:                       3.642   Cond. No.                         567.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [34]:
Usedata2=dataReplace[['NWA_Limited water service','NS_Limited sanitation service','NH_Limited hygiene service ', 'Value' ]]

In [35]:
UsedataValid2=Usedata2.dropna()

In [36]:
UsedataValid2.shape

(28, 4)

In [37]:
new_d2=pd.DataFrame(UsedataValid2,dtype=np.float)

In [38]:
#Regression
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [40]:
X2=new_d2[['NH_Limited hygiene service ','NS_Limited sanitation service', 'Value']]

In [41]:
Y2=new_d2['NWA_Limited water service']

In [42]:
X2=sm.add_constant(X2)
est=sm.OLS(Y2,X2).fit()
est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                OLS Regression Results
=====================================================================================
Dep. Variable:     NWA_Limited water service   R-squared:                       0.215
Model:                                   OLS   Adj. R-squared:                  0.117
Method:                        Least Squares   F-statistic:                     2.190
Date:                       Fri, 08 Nov 2019   Prob (F-statistic):              0.115
Time:                               10:28:43   Log-Likelihood:                -127.99
No. Observations:                         28   AIC:                             264.0
Df Residuals:                             24   BIC:                             269.3
Df Model:                                  3
Covariance Type:                   nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                            33.5743     28.519      1.177      0.251     -25.287      92.435
NH_Limited hygiene service        0.4030      0.183      2.207      0.037       0.026       0.780
NS_Limited sanitation service    -0.1206      0.218     -0.553      0.585      -0.571       0.330
Value                            -0.2736      0.293     -0.934      0.360      -0.878       0.331
==============================================================================
Omnibus:                       15.778   Durbin-Watson:                   1.882
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               16.333
Skew:                           1.650   Prob(JB):                     0.000284
Kurtosis:                       4.765   Cond. No.                         559.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [46]:
#Regression hygie===
import pandas as pd
import numpy as np
import statsmodels.api as sm
X=new_d[['NWA_Basic water service','NS_Basic sanitation service', 'Value']]
Y=new_d['NH_Basic hygiene service']
X=sm.add_constant(X)
est=sm.OLS(Y,X).fit()
est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               OLS Regression Results
====================================================================================
Dep. Variable:     NH_Basic hygiene service   R-squared:                       0.619
Model:                                  OLS   Adj. R-squared:                  0.586
Method:                       Least Squares   F-statistic:                     18.43
Date:                      Fri, 08 Nov 2019   Prob (F-statistic):           2.84e-07
Time:                              11:33:14   Log-Likelihood:                -176.38
No. Observations:                        38   AIC:                             360.8
Df Residuals:                            34   BIC:                             367.3
Df Model:                                 3
Covariance Type:                  nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                         -32.6628     18.242     -1.790      0.082     -69.736       4.410
NWA_Basic water service         0.4576      0.154      2.975      0.005       0.145       0.770
NS_Basic sanitation service     0.5483      0.186      2.944      0.006       0.170       0.927
Value                           0.2059      0.275      0.749      0.459      -0.352       0.764
==============================================================================
Omnibus:                        8.831   Durbin-Watson:                   2.554
Prob(Omnibus):                  0.012   Jarque-Bera (JB):                8.032
Skew:                          -1.099   Prob(JB):                       0.0180
Kurtosis:                       3.494   Cond. No.                         561.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [47]:
#Regression hygie===
import pandas as pd
import numpy as np
import statsmodels.api as sm
X=new_d[['NWA_Basic water service','NH_Basic hygiene service', 'Value']]
Y=new_d['NS_Basic sanitation service']
X=sm.add_constant(X)
est=sm.OLS(Y,X).fit()
est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:     NS_Basic sanitation service   R-squared:                       0.553
Model:                                     OLS   Adj. R-squared:                  0.513
Method:                          Least Squares   F-statistic:                     14.01
Date:                         Fri, 08 Nov 2019   Prob (F-statistic):           4.14e-06
Time:                                 11:34:16   Log-Likelihood:                -168.93
No. Observations:                           38   AIC:                             345.9
Df Residuals:                               34   BIC:                             352.4
Df Model:                                    3
Covariance Type:                     nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       10.4746     15.583      0.672      0.506     -21.194      42.143
NWA_Basic water service      0.0658      0.142      0.465      0.645      -0.222       0.353
NH_Basic hygiene service     0.3705      0.126      2.944      0.006       0.115       0.626
Value                        0.4293      0.215      1.992      0.054      -0.009       0.867
==============================================================================
Omnibus:                        1.797   Durbin-Watson:                   2.085
Prob(Omnibus):                  0.407   Jarque-Bera (JB):                0.831
Skew:                          -0.232   Prob(JB):                        0.660
Kurtosis:                       3.556   Cond. No.                         551.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [48]:
#Regression hygie===
import pandas as pd
import numpy as np
import statsmodels.api as sm
X=new_d[['NWA_Basic water service','NH_Basic hygiene service','NS_Basic sanitation service' ]]
Y=new_d['Value']
X=sm.add_constant(X)
est=sm.OLS(Y,X).fit()
est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Value   R-squared:                       0.420
Model:                            OLS   Adj. R-squared:                  0.369
Method:                 Least Squares   F-statistic:                     8.208
Date:                Fri, 08 Nov 2019   Prob (F-statistic):           0.000304
Time:                        11:34:34   Log-Likelihood:                -158.17
No. Observations:                  38   AIC:                             324.3
Df Residuals:                      34   BIC:                             330.9
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                          54.7495      7.173      7.633      0.000      40.172      69.327
NWA_Basic water service         0.1234      0.105      1.178      0.247      -0.090       0.336
NH_Basic hygiene service        0.0789      0.105      0.749      0.459      -0.135       0.293
NS_Basic sanitation service     0.2436      0.122      1.992      0.054      -0.005       0.492
==============================================================================
Omnibus:                        3.875   Durbin-Watson:                   2.201
Prob(Omnibus):                  0.144   Jarque-Bera (JB):                2.630
Skew:                          -0.593   Prob(JB):                        0.268
Kurtosis:                       3.503   Cond. No.                         322.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""